source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'CEMActivityViewController_Example', :exclusive => true do
  pod 'CEMActivityViewController', :path => '../'
end

target 'CEMActivityViewController_Tests', :exclusive => true do
  pod 'CEMActivityViewController', :path => '../'

#  pod 'FBSnapshotTestCase'
end
