source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'CEMActivityViewController_Example' do
  pod 'CEMActivityViewController', :path => '../'
  
end

target 'CEMActivityViewController_Tests' do
#  pod 'CEMActivityViewController', :path => '../'

#  pod 'FBSnapshotTestCase'
end
