source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!
#install! 'cocoapods',
#:deterministic_uuids => false,

# , :exclusive => true
target 'CEMActivityViewController_Example' do
  
  pod 'CEMActivityViewController', :path => '../'
  
end

target 'CEMActivityViewController_Tests' do
#  pod 'CEMActivityViewController', :path => '../'

#  pod 'FBSnapshotTestCase'
end
